### PR TITLE
Use the dtolnay trick to have 2 versions of failure.

### PR DESCRIPTION
**Pull request by withoutboats**
In order to make breaking changes to failure, we introduce two versions of the crate. Both will be hosted in the repo, forever. Also bring the failure_derive crate (in two versions) into this repo.

As of this PR, there should be no difference between the two repos. In the version 0.2, everything except the macros & derive are re-exported from version 0.1. This is because the macros & derive are the only items that are expected to break between the two versions.

I'd like to get more confidence that I did this correctly and the two versions produce identical APIs, but I'm not certain how (I guess download some major users like cargo and patch them to the 0.2 version.)

### CODE REVIEW

**Comment by dtolnay** [comment]
Hold on, the dtolnay trick would be that 0.1.2 depends on 0.2. This PR looks like the opposite.

**Comment by withoutboats** [comment]
The reason I went the opposite direction is that it guarantees that users will upgrade, whereas I think your original could leave things incorrect sometimes (though cargo may avoid that).

If a user gets version `0.2` in their dependency graph, that introduces a dependency on `0.1.2`, so their previous `0.1.1` dependencies will have to be unified with `0.1.2`. If that didn't happen, what stops them from getting the non-reexporting `0.1.1` version and still getting incompatibility errors?

I guess probably the reason you did it the other way was to reduce build sizes in what will hopefully be the common case in the long term (everyone upgrading to the new version)? Is that right, or are the advantages of your direction different?

**Comment by withoutboats** [comment]
I think probably the reason this hasn't been a problem in practice is that when you add a dependency, cargo regenerates the entire graph and makes no effort to minimize the diff, causing upgrades to the latest versions of unrelated dependencies.

You make a compelling argument, I'll probably reverse it.

**Comment by withoutboats** [comment]
Reversed the direction of the dependencies, changes the new version to 1.0 (planning to make this the only breaking change), and added a `failure_compat_shim` crate to avoid the two rlibs problem, so we can keep testing both versions.

**Pull request merged**
