### PR TITLE
Add `failure_derive` to the example in README.md

### PR DESCRIPTION
**Pull request by Phrohdoh**

### CODE REVIEW

**Comment by Celti** [comment]
Uh... why? `failure` rexports `failure_derive`'s macros, so the `#[macro_use] extern crate failure;` is all that's necessary unless you're messing with `#![no_std]`.

**Comment by Phrohdoh** [comment]
The [announcement post for this crate](https://boats.gitlab.io/blog/post/2017-11-16-announcing-failure/) says:

> A separate crate, failure_derive provides a custom derive, enabling you to derive Fail and Display for your type. This derive doesn’t do anything other than implement these two traits:

```rust
extern crate failure;
#[macro_use] extern crate failure_derive;

#[derive(Debug, Fail)]
#[fail(display = "UTF8 error at index `{}`", index)]
pub struct Utf8Error {
    index: usize,
}
```

---

If `failure_derive` is no longer explicitly need then awesome. I'll close this and update my code.

**Comment by Celti** [comment]
`failure_derive` is automatically rexported as of PR #81, except in the case of `#![no_std]`, as outlined in that PR.

**Comment by Phrohdoh** [comment]
Great to see. Thanks @Celti.

**Pull request closed without merging**
