### PR TITLE
Use a new env var for error backtraces.

### PR DESCRIPTION
**Pull request by withoutboats**

### CODE REVIEW

**Comment by withoutboats** [comment]
cc @cramertj @jsgf

**Comment by cramertj** [comment]
Maybe `RUST_FAILURE_BACKTRACE`? `ERROR_BACKTRACE` could very well overlap with other things in people's environment.

**Comment by withoutboats** [comment]
I changed it to `RUST_ERROR_BACKTRACE`.

I'm not sure about this though.. I think in the long term it would be better for `RUST_BACKTRACE` to turn all backtraces on and have a `RUST_PANIC_BACKTRACE` that only turns on panic backtraces. That way you never need to set two env vars, you just have to decide which env var to set. That would require an upstream patch.

**Comment by withoutboats** [comment]
Talked to @alexcrichton who suggested that at least until we can get `RUST_PANIC_BACKTRACE` upstreamed, we could instead have it so that you can set `RUST_FAILURE_BACKTRACE` to `0` to turn them off. So you have:

* `RUST_BACKTRACE=1`: everything on
* `RUST_FAILURE_BACKTRACE=1`: just failure backtraces
* `RUST_BACKTRACE=1 RUST_FAILURE_BACKTRACE=0`: just panic backtraces

**Comment by withoutboats** [comment]
Implemented that behavior with tests, going to merge it.

**Pull request merged**
